// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getServiceRoleKey() {
  return process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SERVICE_ROLE_KEY;
}

export function getMissingSupabaseAdminEnvVars() {
  return [
    ...(!process.env.SUPABASE_URL ? ['SUPABASE_URL'] : []),
    ...(!getServiceRoleKey() ? ['SERVICE_ROLE_KEY'] : []),
  ];
}

export function hasSupabaseAdminCredentials() {
  return getMissingSupabaseAdminEnvVars().length === 0;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY = getServiceRoleKey();

  const missing = getMissingSupabaseAdminEnvVars();
  if (missing.length > 0) {
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Add the missing value in project Secrets.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY!, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@orizino/supabase/client-server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    const client = _supabaseAdmin ??= createSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
