"use client";
export { default as TableSkeleton } from "./TableSkeleton";
export { default as CardGridSkeleton } from "./CardGridSkeleton";
export { default as FormSkeleton } from "./FormSkeleton";
export { default as DashboardSkeleton } from "./DashboardSkeleton";
export { default as DetailSkeleton } from "./DetailSkeleton";
export { default as ChatSkeleton } from "./ChatSkeleton";
export { default as SectionShimmer } from "./SectionShimmer";
export type { SectionShimmerKind } from "./SectionShimmer";
export { default as AutoSkeleton } from "./AutoSkeleton";
export type { SkeletonVariant } from "./AutoSkeleton";
export * from "./primitives";
